title: Xiaoyang Xie's Homepage
page-top-title: Xiaoyang Xie
top-section-bg-text: Hello, World.
home-subtitle: Xiaoyang Xie&ensp;|&ensp;谢孝洋
copyright-text: '&copy; Xiaoyang Xie 2022-2026. All Rights Reserved.'
